// Copyright © 2026 Apple Inc.

#if FoundationModelsIntegration && canImport(FoundationModels, _version: 2)

import Testing
import Foundation

/// Manifest test that pins the set of golden fixtures used as a
/// change-detection reference for guided generation.
///
/// The goldens are a self-recorded snapshot of the prior guided-generation
/// backend's per-step behavior, replayed to catch functional regressions in
/// the current xgrammar backend. They are not an external correctness oracle
/// and assert nothing about parity with any first-party model.
///
/// The fixtures are not regenerated by this test. They were produced once
/// by an (env-gated) recording harness that no longer lives in-tree, and
/// committed to the repo. This test checks that they remain present and
/// well-formed whenever the integration suite runs so an accidental deletion
/// or corruption is loud, not silent.
///
/// Fixture set:
///   - `tokenizer_qwen25.json` — Qwen2.5-3B vocab size, eos, construction status.
///   - `tokenizer_gemma3.json` — Gemma-3 270M vocab size, eos, construction status.
///   - `schema_tier{1..4}_steps.json` — per-step: mask hex, committed token id,
///     fast-forward token ids, isStop flags. One file per tier schema already
///     defined in `HardReserveStressTests.swift`.
///
/// Malformed-schema error parity is NOT a golden: its inputs are a static
/// inline table in `MalformedSchemaErrorParityTests.swift` (the recorded
/// error fields were never asserted).
///
/// Rollback (`rollback_scenario.json`) is intentionally NOT captured: rollback
/// determinism (commit N, rollback N → identical mask) is a property of any
/// correct matcher and does not require cross-backend parity; it is validated
/// as a standalone determinism test.
@Suite(.serialized)
struct GoldenFixtureManifestTests {

    @Test(
        "All golden fixtures exist and are non-empty well-formed JSON with expected top-level keys"
    )
    func testGoldenFixturesExistAndAreNonEmpty() throws {
        for fixture in Self.expectedFixtures {
            let base = (fixture.filename as NSString).deletingPathExtension
            let ext = (fixture.filename as NSString).pathExtension

            guard let url = fixturesBundle.url(forResource: base, withExtension: ext) else {
                Issue.record(
                    "Expected golden fixture missing: \(fixture.filename). Regenerate the golden fixtures if they are missing."
                )
                continue
            }

            let data: Data
            do {
                data = try Data(contentsOf: url)
            } catch {
                Issue.record("Could not read \(fixture.filename): \(error)")
                continue
            }

            #expect(data.count > 0, "Golden fixture is empty: \(fixture.filename)")

            let decoded: Any
            do {
                decoded = try JSONSerialization.jsonObject(with: data)
            } catch {
                Issue.record("Golden fixture is not valid JSON: \(fixture.filename): \(error)")
                continue
            }

            guard let object = decoded as? [String: Any] else {
                Issue.record(
                    "Golden fixture top-level is not a JSON object: \(fixture.filename)")
                continue
            }

            for requiredKey in fixture.requiredTopLevelKeys {
                #expect(
                    object[requiredKey] != nil,
                    "Golden fixture \(fixture.filename) is missing required top-level key: \(requiredKey)"
                )
            }
        }
    }

    // MARK: - Manifest

    fileprivate struct FixtureSpec {
        let filename: String
        let requiredTopLevelKeys: [String]
    }

    fileprivate static let expectedFixtures: [FixtureSpec] = [
        .init(
            filename: "tokenizer_qwen25.json",
            requiredTopLevelKeys: ["modelId", "vocabSize", "eosTokenId", "constructionStatus"]
        ),
        .init(
            filename: "tokenizer_gemma3.json",
            requiredTopLevelKeys: ["modelId", "vocabSize", "eosTokenId", "constructionStatus"]
        ),
        .init(
            filename: "schema_tier1_steps.json",
            requiredTopLevelKeys: [
                "tier", "modelId", "schema", "document", "vocabSize", "steps",
            ]
        ),
        .init(
            filename: "schema_tier2_steps.json",
            requiredTopLevelKeys: [
                "tier", "modelId", "schema", "document", "vocabSize", "steps",
            ]
        ),
        .init(
            filename: "schema_tier3_steps.json",
            requiredTopLevelKeys: [
                "tier", "modelId", "schema", "document", "vocabSize", "steps",
            ]
        ),
        .init(
            filename: "schema_tier4_steps.json",
            requiredTopLevelKeys: [
                "tier", "modelId", "schema", "document", "vocabSize", "steps",
            ]
        ),
    ]
}

#endif
